# Generated by Django 3.2.4 on 2021-07-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SentimentAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('records', models.IntegerField(max_length=4, null=True)),
                ('text_box', models.TextField(max_length=90000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Analyzed', 'Analyzed'), ('Pending', 'Pending')], max_length=50, null=True)),
            ],
        ),
    ]
