# Generated by Django 3.2.4 on 2021-07-04 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SentimentAnalyzer', '0002_file_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='file',
            name='text_attribute_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SentimentAnalyzer.client'),
        ),
        migrations.AddField(
            model_name='order',
            name='files',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SentimentAnalyzer.file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='records',
            field=models.IntegerField(null=True),
        ),
    ]
