# Generated by Django 3.2.4 on 2021-07-10 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SentimentAnalyzer', '0003_auto_20210704_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='text_attribute_name',
            new_name='review_column_name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='records',
        ),
        migrations.RemoveField(
            model_name='file',
            name='text_box',
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
