# Generated by Django 3.2.4 on 2021-07-10 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SentimentAnalyzer', '0004_auto_20210710_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='username',
        ),
    ]
