# Generated by Django 3.2.4 on 2021-07-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SentimentAnalyzer', '0005_rename_user_client_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='review_column_name',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
