# Generated by Django 3.2.4 on 2021-07-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SentimentAnalyzer', '0006_auto_20210710_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='username',
            new_name='user',
        ),
    ]
