# Generated by Django 3.2.4 on 2021-07-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SentimentAnalyzer', '0008_file_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='review_column_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
